src/Entity/Attempt.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use App\ApiPlatform\Filter\Attempt\TaskFilter;
use  App\ApiPlatform\Filter\Attempt\UserFilter;
use  App\DateTime\DateTime as DT;
use App\Entity\Attempt\Result;
use App\Object\ObjectAccessor;
use App\Serializer\Group;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AttemptRepository")
 * @ApiResource(
 *     order={"id": "DESC"},
 *     normalizationContext={"groups"={Group::ATTEMPT}},
 *     itemOperations={
 *     "get"={"access_control"="is_granted('VIEW', object)"},
 *   "answer"={"access_control"="is_granted('SOLVE', object)", "path"="/attempts/{id}/answer.{_format}", "controller"="App\Controller\Api\AttemptController::answer", "method"="PUT"}
 *     },
 *     collectionOperations={
 * "get"
 *     }
 *     )
 * @ApiFilter(UserFilter::class)
 * @ApiFilter(TaskFilter::class)
 */
class Attempt
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="bigint")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Example", mappedBy="attempt", orphanRemoval=true)
     */
    private $examples;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addTime;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Session", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $session;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Task", inversedBy="attempts")
     */
    private $task;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Settings", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $settings;

    /**
     * @var Result
     * @ORM\OneToOne(targetEntity=Result::class, mappedBy="attempt", cascade={"persist", "remove"})
     */
    private $result;

    public function __construct()
    {
        $this->examples = new ArrayCollection();
        $this->addTime = new \DateTime();
    }

    public function getId(): ?int
    {
        if (null === $this->id) {
            return null;
        }

        return (int) $this->id;
    }

    /**
     * @return Collection|Example[]
     */
    public function getExamples(): Collection
    {
        return $this->examples;
    }

    public function addExample(Example $example): self
    {
        if (!$this->examples->contains($example)) {
            $this->examples[] = $example;
            $example->setAttempt($this);
        }

        return $this;
    }

    public function removeExample(Example $example): self
    {
        if ($this->examples->contains($example)) {
            $this->examples->removeElement($example);
            // set the owning side to null (unless already changed)
            if ($example->getAttempt() === $this) {
                $example->setAttempt(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->getAddTime();
    }

    public function getAddTime(): ?DT
    {
        return DT::createFromDT($this->addTime);
    }

    public function getStartedAt(): DT
    {
        return $this->getAddTime();
    }

    public function setAddTime(\DateTimeInterface $addTime): self
    {
        $this->addTime = $addTime;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(? Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getExamplesCount()
    {
        return $this->getSettings()->getExamplesCount();
    }

    public function getLimitTime(): \DateTimeInterface
    {
        return DT::createFromTimestamp($this->getAddTime()->getTimestamp() + $this->getSettings()->getDuration()->getTimestamp());
    }

    public function getUser(): ?User
    {
        return $this->getSession()->getUser();
    }

    public function getTask(): ?Task
    {
        return $this->task;
    }

    public function setTask(?Task $task): void
    {
        $this->task = $task;
        $this->setSettings($task->getSettings());
    }

    public function getSettings(): ?Settings
    {
        return $this->settings;
    }

    public function setSettings(?Settings $settings): self
    {
        $this->settings = $settings;

        return $this;
    }

    public function getResult(): ?Result
    {
        return $this->result;
    }

    public function setResult(Result $result): self
    {
        $this->result = $result;

        // set the owning side of the relation if necessary
        if ($this !== $result->getAttempt()) {
            $result->setAttempt($this);
        }

        return $this;
    }

    public function isDone(): bool
    {
        return null !== $this->getResult() && 0 === $this->getResult()->getRemainedExamplesCount();
    }

    public function isFinished(): bool
    {
        return true === ObjectAccessor::getNullableTraversedValue($this, 'result.isFinished');
    }
}

src/Entity/Task.php
<?php

namespace App\Entity;

use App\DateTime\DateTime as DT;
use App\Repository\TaskRepository;
use  App\Validator as AppAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Webmozart\Assert\Assert;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="homework")
     */
    private $contractors;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Attempt", mappedBy="task")
     */
    private $attempts;

    /**
     * @ORM\Column(type="smallint")
     * @AppAssert\NumberBetween(minimum=1, maximum=50)
     */
    private $timesCount = 5;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addTime;

    /**
     * @ORM\Column(type="datetime")
     */
    private $limitTime;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Settings", inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $settings;

    public function __construct()
    {
        $this->contractors = new ArrayCollection();
        $this->attempts = new ArrayCollection();
        $this->addTime = new \DateTime();
        $this->limitTime = (new \DateTime())->add(new \DateInterval('P7D'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(User $author): void
    {
        Assert::true($author->isTeacher());
        $this->author = $author;
        $this->setContractors($author->getStudents());
    }

    /**
     * @return Collection|User[]
     */
    public function getContractors(): Collection
    {
        return $this->contractors;
    }

    public function addContractor(User $contractor): self
    {
        if (!$this->contractors->contains($contractor)) {
            $this->contractors[] = $contractor;
        }

        return $this;
    }

    public function removeContractor(User $contractor): self
    {
        if ($this->contractors->contains($contractor)) {
            $this->contractors->removeElement($contractor);
        }

        return $this;
    }

    public function setContractors(Collection $contractors): void
    {
        $this->contractors = $contractors;
    }

    /**
     * @return Collection|Attempt[]
     */
    public function getAttempts(): Collection
    {
        return $this->attempts;
    }

    public function addAttempt(Attempt $attempt): self
    {
        if (!$this->attempts->contains($attempt)) {
            $this->attempts[] = $attempt;
            $attempt->setTask($this);
        }

        return $this;
    }

    public function removeAttempt(Attempt $attempt): self
    {
        if ($this->attempts->contains($attempt)) {
            $this->attempts->removeElement($attempt);
            // set the owning side to null (unless already changed)
            if ($attempt->getTask() === $this) {
                $attempt->setTask(null);
            }
        }

        return $this;
    }

    public function getTimesCount(): ?int
    {
        return $this->timesCount;
    }

    public function setTimesCount(int $timesCount): self
    {
        $this->timesCount = $timesCount;

        return $this;
    }

    public function getAddTime(): ?\DateTimeInterface
    {
        return DT::createFromDT($this->addTime);
    }

    public function setAddTime(\DateTimeInterface $addTime): self
    {
        $this->addTime = $addTime;

        return $this;
    }

    public function getLimitTime(): ?\DateTimeInterface
    {
        return DT::createFromDT($this->limitTime);
    }

    public function setLimitTime(\DateTimeInterface $limitTime): self
    {
        $this->limitTime = $limitTime;

        return $this;
    }

    public function isCreatedBy(User $author): bool
    {
        return $this->author->isEqualTo($author);
    }

    public function getSettings(): ?Settings
    {
        return $this->settings;
    }

    public function setSettings(?Settings $settings): self
    {
        $this->settings = $settings;

        return $this;
    }

    public function getTotalExamplesCount(): int
    {
        return $this->getSettings()->getExamplesCount() * $this->getTimesCount();
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\ApiPlatform\Attribute;
use App\ApiPlatform\Filter\Validation\FilterTaskValidationSubscriber;
use App\ApiPlatform\Filter\Validation\FilterUserValidationSubscriber;
use App\ApiPlatform\Format;
use App\Attempt\EventSubscriber\ShowAttemptsCollectionSubscriber;
use App\Attempt\Example\EventSubscriber\ShowExamplesCollectionSubscriber;
use App\Attempt\Profile\ProfileProviderInterface;
use App\Attempt\Settings\SettingsProviderInterface;
use App\Controller\Traits\CurrentUserProviderTrait;
use App\Controller\Traits\JavascriptParametersTrait;
use App\Entity\Task;
use App\Entity\User;
use App\Entity\User\Role;
use App\Form\TaskType;
use App\Object\ObjectAccessor;
use App\Response\Result\ContractorResult;
use App\Security\Annotation as AppSecurity;
use App\Security\Voter\TaskVoter;
use App\Security\Voter\UserVoter;
use App\Task\Contractor\ContractorProviderInterface;
use App\Task\Contractor\ContractorResultFactoryInterface;
use App\Task\TaskProviderInterface;
use App\Task\TaskResultFactoryInterface;
use App\User\Teacher\Exception\RequiresTeacherAccessException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/task")
 * @IsGranted(Role::USER)
 * @AppSecurity\IsGranted(Role::TEACHER, exception=RequiresTeacherAccessException::class)
 */
final class TaskController extends Controller
{
    use CurrentUserProviderTrait;
    use JavascriptParametersTrait;

    /**
     * @Route("/", name="task_index", methods="GET")
     */
    public function index(): Response
    {
        return $this->render('task/index.html.twig');
    }

    public function tasks(TaskProviderInterface $taskProvider, TaskResultFactoryInterface $taskResultFactory): Response
    {
        $createTaskResult = [$taskResultFactory, 'createTaskResult'];

        return $this->render('task/tasks_widget.html.twig', [
            'actual' => array_map($createTaskResult, $taskProvider->getActualTasksOfCurrentUser()),
            'archive' => array_map($createTaskResult, $taskProvider->getArchiveTasksOfCurrentUser()),
        ]);
    }

    /**
     * @Route("/new/", name="task_new", methods={"GET", "POST"})
     */
    public function new(Request $request, SettingsProviderInterface $settingsProvider, ProfileProviderInterface $profileProvider): Response
    {
        /** @var Task $task */
        $task = ObjectAccessor::initialize(Task::class, [
            'author' => $this->getCurrentUserOrGuest(),
        ]);
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush($task);

            return $this->redirectToRoute('task_index');
        }

        $form->remove('profile');

        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
            'profileProvider' => $profileProvider,
            'currentProfile' => $profileProvider->getCurrentProfile(),
            'publicProfiles' => $profileProvider->getPublicProfiles(),
            'userProfiles' => $profileProvider->getCurrentUserProfiles(),
        ]);
    }

    /**
     * @Route("/{id}/", name="task_show", methods="GET")
     * @IsGranted(TaskVoter::SHOW, subject="task")
     */
    public function show(Task $task, ContractorProviderInterface $contractorProvider, ContractorResultFactoryInterface $contractorResultFactory, TaskResultFactoryInterface $taskResultFactory): Response
    {
        $createContractorResult = function (User $contractor) use ($task, $contractorResultFactory): ContractorResult {
            return $contractorResultFactory->createContractorResult($contractor, $task);
        };

        return $this->render('task/show.html.twig', [
            'taskResult' => $taskResultFactory->createTaskResult($task),
            'solvedTaskContractors' => array_map($createContractorResult, $contractorProvider->getSolvedTaskContractors($task)),
            'notSolvedTaskContractors' => array_map($createContractorResult, $contractorProvider->getNotSolvedTaskContractors($task)),
        ]);
    }

    /**
     * @Route("/{id}/edit/", name="task_edit", methods={"GET", "POST"})
     * @IsGranted(TaskVoter::EDIT, subject="task")
     */
    public function edit(Request $request, Task $task, ProfileProviderInterface $profileProvider): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()
                ->getManager()
                ->flush($task);

            return $this->redirectToRoute('task_index');
        }

        $form->remove('profile');

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
            'profileProvider' => $profileProvider,
            'currentProfile' => $profileProvider->getSettingsOrDefaultProfile($task->getSettings()),
            'publicProfiles' => $profileProvider->getPublicProfiles(),
            'userProfiles' => $profileProvider->getCurrentUserProfiles(),
        ]);
    }

    /**
     * @Route("/{id}/contractor/{contractor_id}/attempts/", name="task_contractor_attempts", methods="GET")
     * @Entity("user", expr="repository.find(contractor_id)")
     * @IsGranted(TaskVoter::SHOW, subject="task")
     * @IsGranted(UserVoter::SHOW_SOLVING_RESULTS, subject="user")
     */
    public function contractorAttempts(Task $task, User $user): Response
    {
        $this->setJavascriptParameters([
            'getAttemptsUrl' => $this->generateUrl(ShowAttemptsCollectionSubscriber::ROUTE, [FilterUserValidationSubscriber::FIELD => $user->getUsername(), FilterTaskValidationSubscriber::FIELD => $task->getId(), Attribute::FORMAT => Format::JSONDT]),
        ]);

        return $this->render('task/contractor_attempts.html.twig', [
            'task' => $task,
            'contractor' => $user,
        ]);
    }

    /**
     * @Route("/{id}/contractor/{contractor_id}/examples/", name="task_contractor_examples", methods="GET")
     * @Entity("user", expr="repository.find(contractor_id)")
     * @IsGranted(TaskVoter::SHOW, subject="task")
     * @IsGranted(UserVoter::SHOW_SOLVING_RESULTS, subject="user")
     */
    public function contractorExamples(Task $task, User $user): Response
    {
        $this->setJavascriptParameters([
            'getExamplesUrl' => $this->generateUrl(ShowExamplesCollectionSubscriber::ROUTE, [FilterUserValidationSubscriber::FIELD => $user->getUsername(), FilterTaskValidationSubscriber::FIELD => $task->getId(), Attribute::FORMAT => Format::JSONDT]),
        ]);

        return $this->render('task/contractor_examples.html.twig', [
            'task' => $task,
            'contractor' => $user,
        ]);
    }

    /**
     * @Route("/{id}/archive/", name="task_archive", methods={"GET"})
     * @IsGranted(TaskVoter::EDIT, subject="task")
     */
    public function archive(Task $task): RedirectResponse
    {
        $lastTime = (new \DateTime())->sub(new \DateInterval('PT1M'));
        $task->setAddTime($lastTime);
        $task->setLimitTime($lastTime);
        $this->getDoctrine()->getManager()->flush($task);

        return $this->redirectToRoute('task_index');
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/_form.html.twig
{{ form_start(form) }}
{%  for field in ['timesCount', 'addTime', 'limitTime'] %}
{{ form_row(form[field]) }}
{%  endfor %}

<h1>Какой профиль будет у домашнего задания?</h1>
{% embed 'profile/list_table.html.twig' with {'title': 'Профили по умолчанию', 'profiles': publicProfiles} %}
    {% block right_table_headers %}
    <th>Выбрать</th>
    {% endblock %}

    {% block right_table_body %}
    <td>
        <input type="radio" name="task[profile]" value="{{  profile.id }}" {{ profile.isEqualTo(currentProfile) ? 'checked' : '' }}>
    </td>
    {% endblock %}
{% endembed %}

{% embed 'profile/list_table.html.twig' with {'title': 'Личные профили', 'profiles': userProfiles} %}
    {% block right_table_headers %}
        <th>Выбрать</th>
    {% endblock %}

    {% block right_table_body %}
        <td>
            <input type="radio" name="{{  form.profile.vars.full_name }}" value="{{  profile.id }}" {{ profileProvider.isCurrentProfile(profile) ? 'checked' : '' }}>
        </td>
    {% endblock %}
{% endembed %}
{{ form_end(form) }}

templates/task/contractor_attempts.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    Архив попыток ({{ contractor.LFName }})
{% endblock %}

{%  block breadcrumbs %}
    {{  include('task/breadcrumbs/contractor/attempts.html.twig') }}
{% endblock %}

{% block main %}
    <h1>Архив попыток</h1>

    {{ include("attempt/list_table.html.twig") }}
{% endblock %}

{% block javascripts %}
    <script src="{{  asset('build/js/task/contractor/attempts.js') }}"></script>
{% endblock %}

templates/task/contractor_examples.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    Архив примеров ({{ contractor.LFName }})
{% endblock %}

{%  block breadcrumbs %}
    {{  include('task/breadcrumbs/contractor/examples.html.twig') }}
{% endblock %}

{% block main %}
    <h1>Архив примеров</h1>

    {{ include("student/examples_table.html.twig") }}
{% endblock %}

{% block javascripts %}
    <script src="{{  asset('build/js/task/contractor/examples.js') }}"></script>
{% endblock %}

templates/task/contractors_table.html.twig
<h2>{{ title }}</h2>

<table class="table table-info">
    <thead>
    <tr>
        <th>№</th>
        <th>Ученик</th>
        <th>Когда была начата последняя попытка?</th>
        <th>Сколько решено примеров?</th>
        <th>Оценка</th>
        <th>Действия</th>
    </tr>
    </thead>
    <tbody>
    {% for number, contractorResponse in sortByDateTime(contractors, 'lastAttempt.startedAt')|reverse %}
        {% set contractor = contractorResponse.contractor %}
        <tr>
            <td>{{ number+1 }}</td>
            <td>
                {{ contractor.lastName }} {{ contractor.firstName }}
            </td>
            <td>
                {{ contractorResponse.lastAttempt is not null ? contractorResponse.lastAttempt.startedAt.timestamp : '-' }}
            </td>
            <td>
                {{ contractorResponse.rightExamplesCount }} из {{ contractorResponse.task.totalExamplesCount }}
            </td>
            <td>{{ contractorResponse.rating ?? '-' }}</td>
            <td>
                <a href="{{ path('task_contractor_attempts', {'id': task.id, 'contractor_id': contractor.id}) }}">
                    Просмотреть попытки
                </a>
                <a href="{{ path('task_contractor_examples', {'id': task.id, 'contractor_id': contractor.id}) }}">
                    Просмотреть примеры
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/task/edit.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    Редактировать  задание
{% endblock %}

{%  block breadcrumbs %}
    {{  include('task/breadcrumbs/edit.html.twig') }}
{% endblock %}

{% block main %}
    {{ parent() }}

    {{ include('task/_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    <script src="{{  asset('build/js/task/edit.js') }}"></script>
{% endblock %}

templates/task/index.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    Домашнее задание
{% endblock %}

{% block breadcrumbs %}
    {{ include('task/breadcrumbs/index.html.twig') }}
{% endblock %}

{% block main %}
    <h1>Домашнее задание</h1>

    {{ render(controller('App\\Controller\\TaskController::tasks')) }}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/js/task/index.js') }}"></script>
{% endblock %}

templates/task/list_table.html.twig
{% macro list_table(title, tasks, isActual) %}
    <h2>{{ title }}</h2>

    <table class="table table-info table-task">
        <thead>
        <tr>
            <th>№</th>
            <th>Задание</th>
            <th>Насколько задание выполнено учениками?</th>
            <th>Сколько учеников выполнило задание?</th>
            <th>Сколько нужно выполнить попыток?</th>
            <th>Сколько нужно решить примеров?</th>
            <th>Когда начинается задание?</th>
            <th>Когда заканчивается задание?</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for number, taskResult in sortByDateTime(tasks, 'task.limitTime')|reverse %}
            {% set task = taskResult.task %}
            <tr>
                <td>{{ number+1 }}</td>
                <td>
                    <a href="{{ path('task_show', {'id': task.id}) }}">{{ task.settings.description }}</a>
                </td>
                <td>{{ taskResult.donePercent }}%</td>
                <td>
                    {{ taskResult.doneContractorsCount }} из {{ task.contractors.count }}
                </td>
                <td>{{ task.timesCount }}</td>
                <td>{{ task.totalExamplesCount }}</td>
                <td>{{ task.addTime }}</td>
                <td>{{ task.limitTime }}</td>
                <td>
                    <a href="{{ path('task_edit', {'id': task.id}) }}">Редактировать</a>

                    {% if isActual %}
                        {% set confirmMessage %}
                            Вы действительно хотите архивировать домашнее задание ({{ task.settings.description }})?
                            При архивации задания время его начала и окончания устанавливается в прошлое.
                            Вы всегда сможете вернуть его в необходимое вам значение на странице редактирования задания.
                        {% endset %}

                        <a href="{{ path('task_archive', {'id': task.id}) }}" role="button" class="btn btn-danger"
                           onclick="return confirm('{{ confirmMessage|toJavascriptString }}')">
                            Архивировать
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}

templates/task/new.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    Создать домашнее задание
{% endblock %}

{%  block breadcrumbs %}
    {{  include('task/breadcrumbs/new.html.twig') }}
{% endblock %}

{% block main %}
    <h1>{{  block('title') }}</h1>

    {{ include('task/_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    <script src="{{  asset('build/js/task/new.js') }}"></script>
{% endblock %}

templates/task/show.html.twig
{% extends 'main.html.twig' %}

{% set task = taskResult.task %}
{% block title %}
    Домашнее задание ({{ task.settings.description }})
{% endblock %}

{% block breadcrumbs %}
    {{ include('task/breadcrumbs/show.html.twig') }}
{% endblock %}

{% block main %}
    {{ parent() }}

    <table class="table table-light">
        <tbody>
        <tr>
            <th>Настройки</th>
            <td><a href="{{ path('settings_show', {'id': task.settings.id}) }}">{{ task.settings.description }}</a></td>
        </tr>
        <tr>
            <th>Количество повторений</th>
            <td>{{ task.timesCount }}</td>
        </tr>
        <tr>
            <th>Время начала</th>
            <td>{{ task.addTime }}</td>
        </tr>
        <tr>
            <th>Время окончания</th>
            <td>{{ task.limitTime }}</td>
        </tr>
        <tr>
            <th>Процент выполнения</th>
            <td>{{ taskResult.donePercent }}%</td>
        </tr>
        </tbody>
    </table>

    <h1>Ученики</h1>
    <div id="active-contractors">
        {% include 'task/contractors_table.html.twig' with {'title': 'Не закончившие выполнение', 'contractors': notSolvedTaskContractors} %}
    </div>

    {% include 'task/contractors_table.html.twig' with {'title': 'Закончившие выполнение', 'contractors': solvedTaskContractors} %}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/js/task/show.js') }}"></script>
{% endblock %}

templates/task/tasks_widget.html.twig
<ul>
    <li><a href="{{ path('task_new') }}" role="button" class="btn btn-success">Создать задание</a></li>
</ul>
{% from 'task/list_table.html.twig' import list_table %}
<div class="actual">
    {{ list_table('Актуальные', actual, true) }}
</div>

<div class="archive">
    {{ list_table('Архив', archive, false) }}
</div>