src/Entity/Attempt.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use App\ApiPlatform\Filter\Attempt\TaskFilter;
use  App\ApiPlatform\Filter\Attempt\UserFilter;
use  App\DateTime\DateTime as DT;
use App\Entity\Attempt\Result;
use App\Object\ObjectAccessor;
use App\Serializer\Group;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AttemptRepository")
 * @ApiResource(
 *     order={"id": "DESC"},
 *     normalizationContext={"groups"={Group::ATTEMPT}},
 *     itemOperations={
 *     "get"={"access_control"="is_granted('VIEW', object)"},
 *   "answer"={"access_control"="is_granted('SOLVE', object)", "path"="/attempts/{id}/answer.{_format}", "controller"="App\Controller\Api\AttemptController::answer", "method"="PUT"}
 *     },
 *     collectionOperations={
 * "get"
 *     }
 *     )
 * @ApiFilter(UserFilter::class)
 * @ApiFilter(TaskFilter::class)
 */
class Attempt
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="bigint")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Example", mappedBy="attempt", orphanRemoval=true)
     */
    private $examples;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addTime;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Session", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $session;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Task", inversedBy="attempts")
     */
    private $task;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Settings", inversedBy="attempts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $settings;

    /**
     * @var Result
     * @ORM\OneToOne(targetEntity=Result::class, mappedBy="attempt", cascade={"persist", "remove"})
     */
    private $result;

    public function __construct()
    {
        $this->examples = new ArrayCollection();
        $this->addTime = new \DateTime();
    }

    public function getId(): ?int
    {
        if (null === $this->id) {
            return null;
        }

        return (int) $this->id;
    }

    /**
     * @return Collection|Example[]
     */
    public function getExamples(): Collection
    {
        return $this->examples;
    }

    public function addExample(Example $example): self
    {
        if (!$this->examples->contains($example)) {
            $this->examples[] = $example;
            $example->setAttempt($this);
        }

        return $this;
    }

    public function removeExample(Example $example): self
    {
        if ($this->examples->contains($example)) {
            $this->examples->removeElement($example);
            // set the owning side to null (unless already changed)
            if ($example->getAttempt() === $this) {
                $example->setAttempt(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->getAddTime();
    }

    public function getAddTime(): ?DT
    {
        return DT::createFromDT($this->addTime);
    }

    public function getStartedAt(): DT
    {
        return $this->getAddTime();
    }

    public function setAddTime(\DateTimeInterface $addTime): self
    {
        $this->addTime = $addTime;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(? Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getExamplesCount()
    {
        return $this->getSettings()->getExamplesCount();
    }

    public function getLimitTime(): \DateTimeInterface
    {
        return DT::createFromTimestamp($this->getAddTime()->getTimestamp() + $this->getSettings()->getDuration()->getTimestamp());
    }

    public function getUser(): ?User
    {
        return $this->getSession()->getUser();
    }

    public function getTask(): ?Task
    {
        return $this->task;
    }

    public function setTask(?Task $task): void
    {
        $this->task = $task;
        $this->setSettings($task->getSettings());
    }

    public function getSettings(): ?Settings
    {
        return $this->settings;
    }

    public function setSettings(?Settings $settings): self
    {
        $this->settings = $settings;

        return $this;
    }

    public function getResult(): ?Result
    {
        return $this->result;
    }

    public function setResult(Result $result): self
    {
        $this->result = $result;

        // set the owning side of the relation if necessary
        if ($this !== $result->getAttempt()) {
            $result->setAttempt($this);
        }

        return $this;
    }

    public function isDone(): bool
    {
        return null !== $this->getResult() && 0 === $this->getResult()->getRemainedExamplesCount();
    }

    public function isFinished(): bool
    {
        return true === ObjectAccessor::getNullableTraversedValue($this, 'result.isFinished');
    }
}

src/Entity/Attempt/Result.php
<?php

namespace App\Entity\Attempt;

use  App\DateTime\DateTime as DT;
use  App\Entity\Attempt;
use  App\Serializer\Group;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * @ORM\Entity
 */
class Result
{
    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var Attempt
     * @ORM\OneToOne(targetEntity="App\Entity\Attempt", inversedBy="result", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $attempt;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime")
     * @Groups({Group::ATTEMPT})
     */
    private $finishedAt;

    /**
     * @var int
     * @ORM\Column(type="smallint")
     * @Groups({Group::ATTEMPT})
     */
    private $errorsCount;

    /**
     * @var int
     * @ORM\Column(type="smallint")
     * @Groups({Group::ATTEMPT})
     */
    private $rating;

    /**
     * @var int
     * @ORM\Column(type="smallint")
     * @Groups({Group::ATTEMPT})
     */
    private $solvedExamplesCount;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAttempt(): ?Attempt
    {
        return $this->attempt;
    }

    public function setAttempt(Attempt $attempt): void
    {
        $this->attempt = $attempt;
    }

    public function getErrorsCount(): ?int
    {
        return $this->errorsCount;
    }

    public function setErrorsCount(int $errorsCount): void
    {
        $this->errorsCount = $errorsCount;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): void
    {
        $this->rating = $rating;
    }

    public function getSolvedExamplesCount(): ?int
    {
        return $this->solvedExamplesCount;
    }

    public function setSolvedExamplesCount(int $solvedExamplesCount): void
    {
        $this->solvedExamplesCount = $solvedExamplesCount;
    }

    public function getFinishedAt(): \DateTimeInterface
    {
        return DT::createFromDT($this->finishedAt);
    }

    public function setFinishedAt(\DateTimeInterface $finishedAt): void
    {
        $this->finishedAt = $finishedAt;
    }

    /**
     * @Groups({Group::ATTEMPT})
     */
    public function getRemainedExamplesCount(): int
    {
        return $this->attempt->getSettings()->getExamplesCount() - $this->getSolvedExamplesCount();
    }

    /**
     * @Groups({Group::ATTEMPT})
     */
    public function getSolvingTime(): \DateTimeInterface
    {
        return DT::createByDifferent($this->getAttempt()->getAddTime(), $this->getFinishedAt());
    }

    /**
     * @Groups({Group::ATTEMPT})
     * @SerializedName("isFinished")
     */
    public function isFinished(): bool
    {
        return time() > $this->getAttempt()->getLimitTime()->getTimestamp()
            or 0 === $this->getRemainedExamplesCount();
    }

    public function getTimePerExample(): ?\DateTimeInterface
    {
        $solvedExamplesCount = $this->getSolvedExamplesCount();

        if (0 === $solvedExamplesCount) {
            return null;
        }

        return DT::createFromTimestamp(
            $this->getSolvingTime()->getTimestamp() / $solvedExamplesCount
        );
    }
}

_smf3/Controller/AttemptController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface as EM;
use Symfony\Component\HttpFoundation\Session\SessionInterface
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Attempt;
use App\Repository\AttemptRepository as AttR;
use App\Repository\ExampleRepository as ExR;
use Symfony\Component\Routing\Annotation\Route;

 /**
*@Route("/attempts")
*/
class AttemptController extends MainController {
private $attR;

public function __construct($AttR $attR) {
$this->attR=$attR;
}

/**
*@Route("/", name="attempt_index")
*/
public function index(AttR $r) {
return $this->render('attempt/index.html.twig', [
"attempts"=>$r->findAllByCurrentUser()
]);
}

/**
*@Route("/{id}/show", name="attempt_show", requirements={"id": "\d+"})
*/
public function show(Attempt $att, ExR $exR, AttR $attR) {
$this->denyAccessUnlessGranted('VIEW', $att);
return $this->render('attempt/show.html.twig', [
"attempt"=>$att,
"examples"=>$exR->findByAttempt($att),
]);
}

/**
*@Route("/{id}", name="attempt_solve", requirements={"id": "\d+"})
*/
public function solve(Attempt $att, ExR $exR, AttR $attR, \Symfony\Component\HttpFoundation\Session\Session $s) {
    if (!$this->isGranted("SOLVE", $att)) {
if ($this->isGranted("VIEW", $att)) return $this->redirectToRoute('attempt_show', ['id'=>$att->getId()]);
else return $this->redirectToRoute("attempt_last");
}
return $this->render('attempt/solve.html.twig', [
"jsParams"=>[
"attData"=>$this->getDataByAtt($att),
'answerRoute'=>$this->generateUrl('attempt_answer', ['id'=>$try->getId()])
]
]);//
}

/**
*@Route("/last", name="attempt_last")
*/
public function last(AttR $attR) {
$att=$attR->findLastByCurrentUserOrNull();
if (!$this->isGranted("SOLVE", $att)) return $this->redirectToRoute("attempt_new");
return $this->redirectToRoute('attempt_solve', ['id'=>$att->getId()]);
}

/**
*@Route("/new", name="attempt_new")
*/
public function new(AttR $attR) {
return $this->redirectToRoute('attempt_solve', ['id'=>$attR->getNewByCurrentUser()->getId()]);
}

/**
*@Route("/{id}/answer", name="attempt_answer")
*@Method("POST")
*/
public function answer(Attempt $att, Request $request, MathMNG $mm, ExR $exR, EM $em) {
if (!$this->isGranted("ANSWER", $att)) return $this->json(['finish'=>true]);

$ex=$exR->findLastByAttemptOrNull($att);
$an=(float) $request->request->get('answer');
$isR=$an === (float) $mm->solveExample($x->getFirst(), $ex->getSecond(), $ex->getSign());
$ex->setAnswer($an)->setIsRight($isR);
$em->flush();

$finish=!$this->isGranted("ANSWER", $att);
if (!$finish) $exR->getNewByAttempt($att);
return $this->json([
'isRight'=>$isR, 
'finish'=>$finish,
'attData'=>$this->getDataByAtt($att),
]);//
}

private function getDataByAtt($att) {
return [];
}
}

src/Controller/Api/AttemptController.php
<?php

namespace App\Controller\Api;

use App\Attempt\AttemptResponseFactoryInterface;
use App\Attempt\AttemptResultProviderInterface;
use App\Attempt\Example\ExampleSolverInterface;
use App\Entity\Attempt;
use App\Response\AttemptResponse;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

final class AttemptController
{
    public function answer(Attempt $data, Request $request, AttemptResponseFactoryInterface $attemptResponseProvider, AttemptResultProviderInterface $attemptResultProvider, EntityManagerInterface $entityManager, ExampleSolverInterface $exampleSolver): array
    {
        $createAnswerAttemptResponseData = function (?bool $isRight, AttemptResponse $attemptResponse): array {
            return [
                'isRight' => $isRight,
                'attempt' => $attemptResponse,
            ];
        };
        $attemptResponse = $attemptResponseProvider->createAttemptResponse($data);

        if ($data->getResult()->isFinished()) {
            return $createAnswerAttemptResponseData(null, $attemptResponse);
        }

        $example = $attemptResponse->getExample()->getExample();

        $answer = (float) $request->request->get('answer');
        $example->setAnswer($answer);
        $example->setIsRight($exampleSolver->isRight($answer, $example));
        $entityManager->flush();
        $attemptResultProvider->updateAttemptResult($data);

        return $createAnswerAttemptResponseData(
            $example->isRight(),
            $attemptResponseProvider->createAttemptResponse($data)
        );
    }
}

templates/attempt/attempts_widget.html.twig
<ul>
    <li>
        <a href="{{  path('attempt_new') }}" role="button" class="btn btn-success">
            Начать новую попытку
        </a>
    </li>
</ul>

{{  include('attempt/list_table.html.twig') }}

templates/attempt/index.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    Архив попыток
{% endblock %}

{%  block breadcrumbs %}
{{  include('attempt/breadcrumbs/index.html.twig') }}
{% endblock %}

{% block main %}
    <div>
        <h1>Архив попыток</h1>
        {{ include("attempt/attempts_widget.html.twig") }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{  asset('build/js/attempt/index.js') }}"></script>
    {% endblock %}

templates/attempt/list_table.html.twig
<table class="table table-info table-attempts">
    <thead>
    <tr>
    <th>№</th>
    <th>Когда начата?</th>
    <th>Использовано времени</th>
    <th>Настройки попытки</th>
    <th>Решено примеров</th>
    <th>Ошибок</th>
    <th>Оценка</th>
    </tr>
    </thead>

    <tbody></tbody>
</table>

templates/attempt/settings.html.twig
{% extends 'settings/show.html.twig' %}

{% set pageTitle = 'Настройки попытки №'~attemptResponse.number %}
{% block title %}
    {{ pageTitle }}
{% endblock %}

{% block breadcrumbs %}
    {{ include('attempt/breadcrumbs/settings.html.twig') }}
{% endblock %}

{% block before_view %}
    <h1>{{ pageTitle }}</h1>
{% endblock %}

templates/attempt/show.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    {{ attemptResponse.title }}
{% endblock %}

{% block breadcrumbs %}
    {{ include('attempt/breadcrumbs/show.html.twig') }}
{% endblock %}

{% block main %}
    <div>
        {% if hasNextTaskAttempt %}
            {% set task = attempt.task %}
            <h1>
                <a href="{{ path('homework_index') }}">
                    Домашнее задание
                </a>
            </h1>
            <ul>
                <li>
                    <a href="{{ path('settings_show', {'id': task.settings.id}) }}">
                        {{ task.settings.description }}
                    </a>
                </li>
                <li>
                    Выполнено попыток: {{  contractorResult.doneAttemptsCount }} из {{  task.timesCount }}
                </li>
                <li>
                    <a href="{{ path('homework_solve', {'id': task.id}) }}" role="button" class="btn btn-success">
                        Продолжить выполнение задания
                    </a>
                </li>
            </ul>
        {% endif %}

        <div>
            <h1>Статистика</h1>

            <ul class="list-group">
                <li>Начало попытки: {{ attempt.createdAt }}</li>
                <li>Конец попытки: {{ attempt.result.finishedAt }}</li>
                <li>Затраченное время: {{ attempt.result.solvingTime.minSecFormat }}
                    из {{ attempt.settings.duration.minSecFormat }}</li>
                <li>Решено примеров: {{ attempt.result.solvedExamplesCount }}
                    из {{ attempt.settings.examplesCount }}</li>
                {% set timePerExample = attempt.result.timePerExample %}
                <li>Секунд/пример: {{ timePerExample is not null ? timePerExample.timestamp : '-' }}</li>
                <li>Ошибок: {{ attempt.result.errorsCount }}</li>
                <li>Оценка: {{ attempt.result.rating }}</li>
                <li>
                    Настройки попытки:
                    <a href="{{ path("attempt_settings", {"id": attempt.id}) }}">{{ attempt.settings.description }}</a>
                </li>
            </ul>
        </div>

        <div>
            <h1>Примеры</h1>

            <table class="table table-striped table-bordered">
                <thead class="thead-light">
                <tr>
                    <th>№</th>
                    <th>Пример</th>
                    <th>Ответ</th>
                    <th>Затраченное время (сек)</th>
                </tr>
                </thead>
                <tbody>
                {% for exampleResponse in exampleResponses|reverse %}
                    {% set example = exampleResponse.example %}
                    {% if not example.isRight %}
                        <tr>
                            <td colspan="4">
                                <h6 class="error">
                                    {{ example.answer is not null ? "Ошибка №"~exampleResponse.errorNumber : "Пример не решен" }}
                                </h6>
                            </td>
                        </tr>
                    {% endif %}
                    <tr class="{{ not example.isRight ? "error" : "" }}">
                        <td>{{ exampleResponse.number }}</td>
                        <td>{{ example }}</td>
                        <td>{{ example.answer ?? '-' }}</td>
                        <td>{{ exampleResponse.solvingTime is not null ? exampleResponse.solvingTime.timestamp : '-' }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/attempt/solve.html.twig
{% extends 'main.html.twig' %}

{% block title %}Попытка №{{ attemptResponse.number }}{% endblock %}

{% block actual_homeworks %}{% endblock %}

{% block main %}
    <div class="attempt-solve">
        <form id="form">
            <h1>Пример №<span id="example-number">*</span></h1>
            <div class="example-area">
<span>
<b><span id="example">* + *</span> =</b>
<input type="text" id="input" required="required" pattern="\d+([.]\d+)?" autocomplete="off">
</span>
            </div>

            <button type="submit" id="submit-button" class="sbtn-primary btn-lg">Ответить</button>
        </form>

        <div class="attempt-solve-statistic">
            <h2>Статистика</h2>
            <ul class="list-group">
                <li class="list-group-item">Ошибок: <span id="errors-count">*</span></li>
                <li class="list-group-item">Осталось времени: <span id="timer">*</span></li>
                <li class="list-group-item">Осталось примеров: <span id="remained-examples-count">*</span></li>
                <li class="list-group-item" id="profile-settings">
                    Настройки попытки:
                    <a href="{{ path("attempt_settings", {"id": attempt.id}) }}">{{ attempt.settings.description }}</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
        <script src="{{  asset('build/js/attempt/solve.js') }}"></script>
{% endblock %}